install:
 - source ./support/texlive.sh

cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive

script:
 - make 

#notifications:
#  email:
#    recipients:
#      - deimantas.galcius@gmail.com
#    on_success: change
#    on_failure: always
#    on_start:   never
