#!/usr/bin/env bash
#
# Summary: process *.fls file, output *.d file (Makefile format)
#          with  lists of dependencies and derived files.
#          Second optional param is for removing from deps
#
# Usage: lg2htmldir foo.lg ./htmldir/foo/
#
# 
#
set -x


input=$1
stem=${1%.*}
lgfile=$stem.lg
htmldir=$2/$stem

lg2html ()
{
  input=$1
  stem=${1%.*}

  echo Processing $stem
  mkdir -p $2

  grep "File: $stem" $input | awk -v outdir=$2 '{system("[ -f "$2" ] &&  mv -f " $2" "outdir)}' 
}

lg2html $lgfile $htmldir



